import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Loading from "@/app/loading"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="Menu">
        <Link href={'/pages/Blog'}>Blog</Link>
        <Link href={'/pages/Form'}>Form</Link>
        <Link href={'/pages/about'}>About</Link>
        <Link href={'/pages/contact'}>Contact</Link>
        <Link href={'/'}>Home</Link>
        <Link href={'/pages/test'}>Test</Link>
        </nav>
        {children}
      </body>
    </html>
  );
} 
